import {
  DollarSign,
  Home,
  ShoppingCart,
  Lightbulb,
  Car,
  ShoppingBag,
  Briefcase,
  Utensils,
  Smartphone,
  LucideIcon,
} from "lucide-react";

export const categoryIcons: Record<string, LucideIcon> = {
  DollarSign,
  Home,
  ShoppingCart,
  Lightbulb,
  Car,
  ShoppingBag,
  Briefcase,
  Utensils,
  Smartphone,
};

export const categories: Category[] = [
  {
    name: "Salary",
    value: "Salary",
    color: "green",
    iconName: "DollarSign",
    type: "income",
  },
  {
    name: "Housing",
    value: "Housing",
    color: "red",
    iconName: "Home",
    type: "expense",
  },
  {
    name: "Groceries",
    value: "Groceries",
    color: "blue",
    iconName: "ShoppingCart",
    type: "expense",
  },
  {
    name: "Utilities",
    value: "Utilities",
    color: "yellow",
    iconName: "Lightbulb",
    type: "expense",
  },
  {
    name: "Transport",
    value: "Transport",
    color: "violet",
    iconName: "Car",
    type: "expense",
  },
  {
    name: "Shopping",
    value: "Shopping",
    color: "pink",
    iconName: "ShoppingBag",
    type: "expense",
  },
  {
    name: "Income",
    value: "Income",
    color: "green",
    iconName: "Briefcase",
    type: "income",
  },
  {
    name: "Food and beverage",
    value: "Food and beverage",
    color: "orange",
    iconName: "Utensils",
    type: "expense",
  },
  {
    name: "Mobile Phone",
    value: "Mobile Phone",
    color: "yellow",
    iconName: "Smartphone",
    type: "expense",
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: 1,
    merchantName: "Google",
    amount: 5000,
    account: "Checking",
    category: {
      name: "Salary",
      iconName: "DollarSign",
      color: "green",
      type: "income",
    },
    date: "2025-05-31",
    merchantLogo: "https://logo.clearbit.com/google.com",
  },
  {
    id: 3,
    merchantName: "Whole Foods",
    amount: -150,
    account: "Credit Card",
    category: {
      name: "Groceries",
      iconName: "ShoppingCart",
      color: "blue",
      type: "expense",
    },
    date: "2025-06-02",
    merchantLogo: "https://logo.clearbit.com/wholefoodsmarket.com",
  },
  {
    id: 4,
    merchantName: "Con Edison",
    amount: -80,
    account: "Checking",
    category: {
      name: "Utilities",
      iconName: "Lightbulb",
      color: "yellow",
      type: "expense",
    },
    date: "2025-06-03",
    merchantLogo: "https://logo.clearbit.com/coned.com",
  },
  {
    id: 5,
    merchantName: "Uber",
    amount: -45,
    account: "Savings",
    category: {
      name: "Transport",
      iconName: "Car",
      color: "violet",
      type: "expense",
    },
    date: "2025-06-03",
    merchantLogo: "https://logo.clearbit.com/uber.com",
  },
  {
    id: 6,
    merchantName: "Amazon",
    amount: -200,
    account: "Credit Card",
    category: {
      name: "Shopping",
      iconName: "ShoppingBag",
      color: "pink",
      type: "expense",
    },
    date: "2025-06-04",
    merchantLogo: "https://logo.clearbit.com/amazon.com",
  },
  {
    id: 7,
    merchantName: "Freelance Client A",
    amount: 1200,
    account: "Paypal",
    category: {
      name: "Income",
      iconName: "Briefcase",
      color: "green",
      type: "income",
    },
    date: "2025-06-05",
    merchantLogo: "https://logo.clearbit.com/paypal.com",
  },
  {
    id: 8,
    merchantName: "The Spotted Pig",
    amount: -70,
    account: "Credit Card",
    category: {
      name: "Food and beverage",
      iconName: "Utensils",
      color: "orange",
      type: "expense",
    },
    date: "2025-06-05",
    merchantLogo: "https://logo.clearbit.com/thespottedpig.com",
  },
  {
    id: 9,
    merchantName: "Verizon",
    amount: -60,
    account: "Checking",
    category: {
      name: "Utilities",
      iconName: "Smartphone",
      color: "yellow",
      type: "expense",
    },
    date: "2025-06-06",
    merchantLogo: "https://logo.clearbit.com/verizon.com",
  },
  {
    id: 10,
    merchantName: "Local Coffee Shop",
    amount: -8.5,
    account: "Credit Card",
    category: {
      name: "Food and beverage",
      iconName: "Utensils",
      color: "orange",
      type: "expense",
    },
    date: "2025-06-07",
    merchantLogo: null,
  },
  {
    id: 11,
    merchantName: "Street Vendor",
    amount: -12.0,
    account: "Cash",
    category: {
      name: "Food and beverage",
      iconName: "Utensils",
      color: "orange",
      type: "expense",
    },
    date: "2025-06-07",
    merchantLogo: null,
  },
  {
    id: 12,
    merchantName: "Neighborhood Laundry",
    amount: -25.0,
    account: "Checking",
    category: {
      name: "Utilities",
      iconName: "Lightbulb",
      color: "yellow",
      type: "expense",
    },
    date: "2025-06-08",
    merchantLogo: null,
  },
];
