import {
  DollarSign,
  Home,
  ShoppingCart,
  Lightbulb,
  Car,
  ShoppingBag,
  Briefcase,
  Utensils,
  Smartphone,
  Music,
  PiggyBank,
  BanknoteArrowUp,
  BanknoteArrowDown,
  LucideIcon,
} from "lucide-react";

export const categoryColors: Record<CategoryColor, string> = {
  red: "text-red-500",
  yellow: "text-yellow-500",
  orange: "text-orange-500",
  blue: "text-blue-500",
  violet: "text-violet-500",
  pink: "text-pink-500",
  green: "text-primary",
};

export const categoryIcons: Record<string, LucideIcon> = {
  DollarSign,
  Home,
  ShoppingCart,
  Lightbulb,
  Car,
  ShoppingBag,
  Briefcase,
  Utensils,
  Smartphone,
  Music,
  PiggyBank,
  BanknoteArrowUp,
  BanknoteArrowDown,
};

export const categories: Category[] = [
  {
    name: "Salary",
    color: "blue",
    iconName: "Briefcase",
    type: "income",
  },
  {
    name: "Other Income",
    color: "green",
    iconName: "BanknoteArrowUp",
    type: "income",
  },
  {
    name: "Housing",
    color: "red",
    iconName: "Home",
    type: "expense",
    budget: 1500,
  },
  {
    name: "Groceries",
    color: "blue",
    iconName: "ShoppingCart",
    type: "expense",
    budget: 450,
  },
  {
    name: "Utilities",
    color: "yellow",
    iconName: "Lightbulb",
    type: "expense",
    budget: 150,
  },
  {
    name: "Transport",
    color: "violet",
    iconName: "Car",
    type: "expense",
    budget: 50,
  },
  {
    name: "Shopping",
    color: "pink",
    iconName: "ShoppingBag",
    type: "expense",
    budget: 100,
  },
  {
    name: "Entertainment",
    color: "orange",
    iconName: "Music",
    type: "expense",
    budget: 50,
  },
  {
    name: "Other Expense",
    color: "red",
    iconName: "BanknoteArrowDown",
    type: "expense",
  },
];

export const mockTransactions: Transaction[] = [
  {
    $id: 1,
    merchantName: "Google",
    amount: 5000,
    account: "Checking",
    category: {
      name: "Salary",
      iconName: "DollarSign",
      color: "green",
      type: "income",
    },
    date: "2025-05-31",
    merchantLogo: "https://logo.clearbit.com/google.com",
  },
  {
    $id: 3,
    merchantName: "Whole Foods",
    amount: -150,
    account: "Credit Card",
    category: {
      name: "Groceries",
      iconName: "ShoppingCart",
      color: "blue",
      type: "expense",
    },
    date: "2025-06-02",
    merchantLogo: "https://logo.clearbit.com/wholefoodsmarket.com",
  },
  {
    $id: 5,
    merchantName: "Uber",
    amount: -45,
    account: "Savings",
    category: {
      name: "Transport",
      iconName: "Car",
      color: "violet",
      type: "expense",
    },
    date: "2025-06-03",
    merchantLogo: "https://logo.clearbit.com/uber.com",
  },
  {
    $id: 6,
    merchantName: "Amazon",
    amount: -200,
    account: "Credit Card",
    category: {
      name: "Shopping",
      iconName: "ShoppingBag",
      color: "pink",
      type: "expense",
    },
    date: "2025-06-04",
    merchantLogo: "https://logo.clearbit.com/amazon.com",
  },
  {
    $id: 7,
    merchantName: "Freelance Client A",
    amount: 1200,
    account: "Paypal",
    category: {
      name: "Income",
      iconName: "Briefcase",
      color: "green",
      type: "income",
    },
    date: "2025-06-05",
    merchantLogo: "https://logo.clearbit.com/paypal.com",
  },
  {
    $id: 8,
    merchantName: "The Spotted Pig",
    amount: -70,
    account: "Credit Card",
    category: {
      name: "Food and beverage",
      iconName: "Utensils",
      color: "orange",
      type: "expense",
    },
    date: "2025-06-05",
    merchantLogo: "https://logo.clearbit.com/thespottedpig.com",
  },
  {
    $id: 9,
    merchantName: "Verizon",
    amount: -60,
    account: "Checking",
    category: {
      name: "Utilities",
      iconName: "Smartphone",
      color: "yellow",
      type: "expense",
    },
    date: "2025-06-06",
    merchantLogo: "https://logo.clearbit.com/verizon.com",
  },
  {
    $id: 10,
    merchantName: "Local Coffee Shop",
    amount: -8.5,
    account: "Credit Card",
    category: {
      name: "Food and beverage",
      iconName: "Utensils",
      color: "orange",
      type: "expense",
    },
    date: "2025-06-07",
    merchantLogo: null,
  },
  {
    $id: 11,
    merchantName: "Street Vendor",
    amount: -12.0,
    account: "Cash",
    category: {
      name: "Food and beverage",
      iconName: "Utensils",
      color: "orange",
      type: "expense",
    },
    date: "2025-06-07",
    merchantLogo: null,
  },
  {
    $id: 12,
    merchantName: "Neighborhood Laundry",
    amount: -25.0,
    account: "Checking",
    category: {
      name: "Utilities",
      iconName: "Lightbulb",
      color: "yellow",
      type: "expense",
    },
    date: "2025-06-08",
    merchantLogo: null,
  },
];
